// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-jobs/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreateDao creates a new instance of MockItemCreateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateDao {
	mock := &MockItemCreateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateDao is an autogenerated mock type for the ItemCreateDao type
type MockItemCreateDao struct {
	mock.Mock
}

type MockItemCreateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateDao) EXPECT() *MockItemCreateDao_Expecter {
	return &MockItemCreateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateDao
func (_mock *MockItemCreateDao) Exec(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemCreateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemCreateRequest
func (_e *MockItemCreateDao_Expecter) Exec(ctx any, request any) *MockItemCreateDao_Exec_Call {
	return &MockItemCreateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemCreateRequest)) *MockItemCreateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemCreateRequest) (*dao.Item, error)) *MockItemCreateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteDao creates a new instance of MockItemDeleteDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteDao {
	mock := &MockItemDeleteDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteDao is an autogenerated mock type for the ItemDeleteDao type
type MockItemDeleteDao struct {
	mock.Mock
}

type MockItemDeleteDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteDao) EXPECT() *MockItemDeleteDao_Expecter {
	return &MockItemDeleteDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteDao
func (_mock *MockItemDeleteDao) Exec(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemDeleteRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemDeleteRequest
func (_e *MockItemDeleteDao_Expecter) Exec(ctx any, request any) *MockItemDeleteDao_Exec_Call {
	return &MockItemDeleteDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemDeleteRequest)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) Return(item *dao.Item, err error) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeleteDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemDeleteRequest) (*dao.Item, error)) *MockItemDeleteDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetDao creates a new instance of MockItemGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetDao {
	mock := &MockItemGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetDao is an autogenerated mock type for the ItemGetDao type
type MockItemGetDao struct {
	mock.Mock
}

type MockItemGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetDao) EXPECT() *MockItemGetDao_Expecter {
	return &MockItemGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetDao
func (_mock *MockItemGetDao) Exec(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemGetRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemGetRequest
func (_e *MockItemGetDao_Expecter) Exec(ctx any, request any) *MockItemGetDao_Exec_Call {
	return &MockItemGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemGetRequest)) *MockItemGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetDao_Exec_Call) Return(item *dao.Item, err error) *MockItemGetDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemGetRequest) (*dao.Item, error)) *MockItemGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListDao creates a new instance of MockItemListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListDao {
	mock := &MockItemListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListDao is an autogenerated mock type for the ItemListDao type
type MockItemListDao struct {
	mock.Mock
}

type MockItemListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListDao) EXPECT() *MockItemListDao_Expecter {
	return &MockItemListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListDao
func (_mock *MockItemListDao) Exec(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) ([]*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemListRequest) []*dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemListRequest
func (_e *MockItemListDao_Expecter) Exec(ctx any, request any) *MockItemListDao_Exec_Call {
	return &MockItemListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemListRequest)) *MockItemListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListDao_Exec_Call) Return(items []*dao.Item, err error) *MockItemListDao_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemListRequest) ([]*dao.Item, error)) *MockItemListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateDao creates a new instance of MockItemUpdateDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateDao {
	mock := &MockItemUpdateDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateDao is an autogenerated mock type for the ItemUpdateDao type
type MockItemUpdateDao struct {
	mock.Mock
}

type MockItemUpdateDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateDao) EXPECT() *MockItemUpdateDao_Expecter {
	return &MockItemUpdateDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateDao
func (_mock *MockItemUpdateDao) Exec(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) (*dao.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.ItemUpdateRequest) *dao.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.ItemUpdateRequest
func (_e *MockItemUpdateDao_Expecter) Exec(ctx any, request any) *MockItemUpdateDao_Exec_Call {
	return &MockItemUpdateDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateDao_Exec_Call) Run(run func(ctx context.Context, request *dao.ItemUpdateRequest)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) Return(item *dao.Item, err error) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdateDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.ItemUpdateRequest) (*dao.Item, error)) *MockItemUpdateDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobClaimDao creates a new instance of MockJobClaimDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobClaimDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobClaimDao {
	mock := &MockJobClaimDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobClaimDao is an autogenerated mock type for the JobClaimDao type
type MockJobClaimDao struct {
	mock.Mock
}

type MockJobClaimDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobClaimDao) EXPECT() *MockJobClaimDao_Expecter {
	return &MockJobClaimDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobClaimDao
func (_mock *MockJobClaimDao) Exec(ctx context.Context, request *dao.JobClaimRequest) ([]*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobClaimRequest) ([]*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobClaimRequest) []*dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobClaimRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobClaimDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobClaimDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobClaimRequest
func (_e *MockJobClaimDao_Expecter) Exec(ctx any, request any) *MockJobClaimDao_Exec_Call {
	return &MockJobClaimDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobClaimDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobClaimRequest)) *MockJobClaimDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobClaimRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobClaimRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobClaimDao_Exec_Call) Return(jobs []*dao.Job, err error) *MockJobClaimDao_Exec_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobClaimDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobClaimRequest) ([]*dao.Job, error)) *MockJobClaimDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobCountPendingDao creates a new instance of MockJobCountPendingDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobCountPendingDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobCountPendingDao {
	mock := &MockJobCountPendingDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobCountPendingDao is an autogenerated mock type for the JobCountPendingDao type
type MockJobCountPendingDao struct {
	mock.Mock
}

type MockJobCountPendingDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobCountPendingDao) EXPECT() *MockJobCountPendingDao_Expecter {
	return &MockJobCountPendingDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobCountPendingDao
func (_mock *MockJobCountPendingDao) Exec(ctx context.Context) (*dao.JobPendingStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.JobPendingStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dao.JobPendingStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dao.JobPendingStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.JobPendingStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobCountPendingDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobCountPendingDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobCountPendingDao_Expecter) Exec(ctx any) *MockJobCountPendingDao_Exec_Call {
	return &MockJobCountPendingDao_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockJobCountPendingDao_Exec_Call) Run(run func(ctx context.Context)) *MockJobCountPendingDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobCountPendingDao_Exec_Call) Return(jobPendingStats *dao.JobPendingStats, err error) *MockJobCountPendingDao_Exec_Call {
	_c.Call.Return(jobPendingStats, err)
	return _c
}

func (_c *MockJobCountPendingDao_Exec_Call) RunAndReturn(run func(ctx context.Context) (*dao.JobPendingStats, error)) *MockJobCountPendingDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobEnqueueDao creates a new instance of MockJobEnqueueDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobEnqueueDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobEnqueueDao {
	mock := &MockJobEnqueueDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobEnqueueDao is an autogenerated mock type for the JobEnqueueDao type
type MockJobEnqueueDao struct {
	mock.Mock
}

type MockJobEnqueueDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobEnqueueDao) EXPECT() *MockJobEnqueueDao_Expecter {
	return &MockJobEnqueueDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobEnqueueDao
func (_mock *MockJobEnqueueDao) Exec(ctx context.Context, request *dao.JobEnqueueRequest) (*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobEnqueueRequest) (*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobEnqueueRequest) *dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobEnqueueRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobEnqueueDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobEnqueueDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobEnqueueRequest
func (_e *MockJobEnqueueDao_Expecter) Exec(ctx any, request any) *MockJobEnqueueDao_Exec_Call {
	return &MockJobEnqueueDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobEnqueueDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobEnqueueRequest)) *MockJobEnqueueDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobEnqueueRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobEnqueueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobEnqueueDao_Exec_Call) Return(job *dao.Job, err error) *MockJobEnqueueDao_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobEnqueueDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobEnqueueRequest) (*dao.Job, error)) *MockJobEnqueueDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobGetDao creates a new instance of MockJobGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobGetDao {
	mock := &MockJobGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobGetDao is an autogenerated mock type for the JobGetDao type
type MockJobGetDao struct {
	mock.Mock
}

type MockJobGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobGetDao) EXPECT() *MockJobGetDao_Expecter {
	return &MockJobGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobGetDao
func (_mock *MockJobGetDao) Exec(ctx context.Context, request *dao.JobGetRequest) (*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobGetRequest) (*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobGetRequest) *dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobGetRequest
func (_e *MockJobGetDao_Expecter) Exec(ctx any, request any) *MockJobGetDao_Exec_Call {
	return &MockJobGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobGetRequest)) *MockJobGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobGetDao_Exec_Call) Return(job *dao.Job, err error) *MockJobGetDao_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobGetRequest) (*dao.Job, error)) *MockJobGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobSettleSettleDao creates a new instance of MockJobSettleSettleDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobSettleSettleDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobSettleSettleDao {
	mock := &MockJobSettleSettleDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobSettleSettleDao is an autogenerated mock type for the JobSettleSettleDao type
type MockJobSettleSettleDao struct {
	mock.Mock
}

type MockJobSettleSettleDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobSettleSettleDao) EXPECT() *MockJobSettleSettleDao_Expecter {
	return &MockJobSettleSettleDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobSettleSettleDao
func (_mock *MockJobSettleSettleDao) Exec(ctx context.Context, request *dao.JobSettleRequest) (*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobSettleRequest) (*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobSettleRequest) *dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobSettleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobSettleSettleDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobSettleSettleDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobSettleRequest
func (_e *MockJobSettleSettleDao_Expecter) Exec(ctx any, request any) *MockJobSettleSettleDao_Exec_Call {
	return &MockJobSettleSettleDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobSettleSettleDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobSettleRequest)) *MockJobSettleSettleDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobSettleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobSettleSettleDao_Exec_Call) Return(job *dao.Job, err error) *MockJobSettleSettleDao_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobSettleSettleDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobSettleRequest) (*dao.Job, error)) *MockJobSettleSettleDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobSettleRequeueDao creates a new instance of MockJobSettleRequeueDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobSettleRequeueDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobSettleRequeueDao {
	mock := &MockJobSettleRequeueDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobSettleRequeueDao is an autogenerated mock type for the JobSettleRequeueDao type
type MockJobSettleRequeueDao struct {
	mock.Mock
}

type MockJobSettleRequeueDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobSettleRequeueDao) EXPECT() *MockJobSettleRequeueDao_Expecter {
	return &MockJobSettleRequeueDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobSettleRequeueDao
func (_mock *MockJobSettleRequeueDao) Exec(ctx context.Context, request *dao.JobRequeueRequest) (*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobRequeueRequest) (*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobRequeueRequest) *dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobRequeueRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobSettleRequeueDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobSettleRequeueDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobRequeueRequest
func (_e *MockJobSettleRequeueDao_Expecter) Exec(ctx any, request any) *MockJobSettleRequeueDao_Exec_Call {
	return &MockJobSettleRequeueDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobSettleRequeueDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobRequeueRequest)) *MockJobSettleRequeueDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobRequeueRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobRequeueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobSettleRequeueDao_Exec_Call) Return(job *dao.Job, err error) *MockJobSettleRequeueDao_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobSettleRequeueDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobRequeueRequest) (*dao.Job, error)) *MockJobSettleRequeueDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobSettleGetDao creates a new instance of MockJobSettleGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobSettleGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobSettleGetDao {
	mock := &MockJobSettleGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobSettleGetDao is an autogenerated mock type for the JobSettleGetDao type
type MockJobSettleGetDao struct {
	mock.Mock
}

type MockJobSettleGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobSettleGetDao) EXPECT() *MockJobSettleGetDao_Expecter {
	return &MockJobSettleGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobSettleGetDao
func (_mock *MockJobSettleGetDao) Exec(ctx context.Context, request *dao.JobGetByIDRequest) (*dao.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobGetByIDRequest) (*dao.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.JobGetByIDRequest) *dao.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.JobGetByIDRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobSettleGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobSettleGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.JobGetByIDRequest
func (_e *MockJobSettleGetDao_Expecter) Exec(ctx any, request any) *MockJobSettleGetDao_Exec_Call {
	return &MockJobSettleGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobSettleGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.JobGetByIDRequest)) *MockJobSettleGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.JobGetByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.JobGetByIDRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobSettleGetDao_Exec_Call) Return(job *dao.Job, err error) *MockJobSettleGetDao_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobSettleGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.JobGetByIDRequest) (*dao.Job, error)) *MockJobSettleGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
