// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkgmocks

import (
	"context"

	"github.com/a-novel-kit/golib/grpcf/proto/gen"
	"github.com/a-novel/service-jobs/pkg/go"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() {
	_mock.Called()
	return
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type MockClient
func (_mock *MockClient) Status(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption) (*servicejobs.StatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *servicejobs.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) (*servicejobs.StatusResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) *servicejobs.StatusResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.StatusRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) Status(ctx any, req any, opts ...any) *MockClient_Status_Call {
	return &MockClient_Status_Call{Call: _e.mock.On("Status",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_Status_Call) Run(run func(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption)) *MockClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.StatusRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.StatusRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Status_Call) Return(v *servicejobs.StatusResponse, err error) *MockClient_Status_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_Status_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption) (*servicejobs.StatusResponse, error)) *MockClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// UnaryEcho provides a mock function for the type MockClient
func (_mock *MockClient) UnaryEcho(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnaryEcho")
	}

	var r0 *golibproto.UnaryEchoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) *golibproto.UnaryEchoResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golibproto.UnaryEchoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UnaryEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnaryEcho'
type MockClient_UnaryEcho_Call struct {
	*mock.Call
}

// UnaryEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - req *golibproto.UnaryEchoRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) UnaryEcho(ctx any, req any, opts ...any) *MockClient_UnaryEcho_Call {
	return &MockClient_UnaryEcho_Call{Call: _e.mock.On("UnaryEcho",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_UnaryEcho_Call) Run(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption)) *MockClient_UnaryEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *golibproto.UnaryEchoRequest
		if args[1] != nil {
			arg1 = args[1].(*golibproto.UnaryEchoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_UnaryEcho_Call) Return(unaryEchoResponse *golibproto.UnaryEchoResponse, err error) *MockClient_UnaryEcho_Call {
	_c.Call.Return(unaryEchoResponse, err)
	return _c
}

func (_c *MockClient_UnaryEcho_Call) RunAndReturn(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)) *MockClient_UnaryEcho_Call {
	_c.Call.Return(run)
	return _c
}
