// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkgmocks

import (
	"context"

	"github.com/a-novel-kit/golib/grpcf/proto/gen"
	"github.com/a-novel/service-jobs/internal/handlers/protogen"
	"github.com/a-novel/service-jobs/pkg/go"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

// NewMockJobWatchClient creates a new instance of MockJobWatchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobWatchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobWatchClient {
	mock := &MockJobWatchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobWatchClient is an autogenerated mock type for the JobWatchClient type
type MockJobWatchClient struct {
	mock.Mock
}

type MockJobWatchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobWatchClient) EXPECT() *MockJobWatchClient_Expecter {
	return &MockJobWatchClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobWatchClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockJobWatchClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockJobWatchClient_Expecter) CloseSend() *MockJobWatchClient_CloseSend_Call {
	return &MockJobWatchClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockJobWatchClient_CloseSend_Call) Run(run func()) *MockJobWatchClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobWatchClient_CloseSend_Call) Return(err error) *MockJobWatchClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobWatchClient_CloseSend_Call) RunAndReturn(run func() error) *MockJobWatchClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockJobWatchClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockJobWatchClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockJobWatchClient_Expecter) Context() *MockJobWatchClient_Context_Call {
	return &MockJobWatchClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockJobWatchClient_Context_Call) Run(run func()) *MockJobWatchClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobWatchClient_Context_Call) Return(context1 context.Context) *MockJobWatchClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockJobWatchClient_Context_Call) RunAndReturn(run func() context.Context) *MockJobWatchClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobWatchClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockJobWatchClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockJobWatchClient_Expecter) Header() *MockJobWatchClient_Header_Call {
	return &MockJobWatchClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockJobWatchClient_Header_Call) Run(run func()) *MockJobWatchClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobWatchClient_Header_Call) Return(mD metadata.MD, err error) *MockJobWatchClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockJobWatchClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockJobWatchClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) Recv() (*protogen.JobWatchResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *protogen.JobWatchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*protogen.JobWatchResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *protogen.JobWatchResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protogen.JobWatchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobWatchClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockJobWatchClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockJobWatchClient_Expecter) Recv() *MockJobWatchClient_Recv_Call {
	return &MockJobWatchClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockJobWatchClient_Recv_Call) Run(run func()) *MockJobWatchClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobWatchClient_Recv_Call) Return(jobWatchResponse *protogen.JobWatchResponse, err error) *MockJobWatchClient_Recv_Call {
	_c.Call.Return(jobWatchResponse, err)
	return _c
}

func (_c *MockJobWatchClient_Recv_Call) RunAndReturn(run func() (*protogen.JobWatchResponse, error)) *MockJobWatchClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobWatchClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockJobWatchClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockJobWatchClient_Expecter) RecvMsg(m any) *MockJobWatchClient_RecvMsg_Call {
	return &MockJobWatchClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockJobWatchClient_RecvMsg_Call) Run(run func(m any)) *MockJobWatchClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobWatchClient_RecvMsg_Call) Return(err error) *MockJobWatchClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobWatchClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockJobWatchClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobWatchClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockJobWatchClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockJobWatchClient_Expecter) SendMsg(m any) *MockJobWatchClient_SendMsg_Call {
	return &MockJobWatchClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockJobWatchClient_SendMsg_Call) Run(run func(m any)) *MockJobWatchClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobWatchClient_SendMsg_Call) Return(err error) *MockJobWatchClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobWatchClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockJobWatchClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockJobWatchClient
func (_mock *MockJobWatchClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockJobWatchClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockJobWatchClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockJobWatchClient_Expecter) Trailer() *MockJobWatchClient_Trailer_Call {
	return &MockJobWatchClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockJobWatchClient_Trailer_Call) Run(run func()) *MockJobWatchClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobWatchClient_Trailer_Call) Return(mD metadata.MD) *MockJobWatchClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockJobWatchClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockJobWatchClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() {
	_mock.Called()
	return
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// JobClaim provides a mock function for the type MockClient
func (_mock *MockClient) JobClaim(ctx context.Context, req *servicejobs.JobClaimRequest, opts ...grpc.CallOption) (*servicejobs.JobClaimResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobClaim")
	}

	var r0 *servicejobs.JobClaimResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobClaimRequest, ...grpc.CallOption) (*servicejobs.JobClaimResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobClaimRequest, ...grpc.CallOption) *servicejobs.JobClaimResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobClaimResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobClaimRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JobClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobClaim'
type MockClient_JobClaim_Call struct {
	*mock.Call
}

// JobClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.JobClaimRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JobClaim(ctx any, req any, opts ...any) *MockClient_JobClaim_Call {
	return &MockClient_JobClaim_Call{Call: _e.mock.On("JobClaim",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_JobClaim_Call) Run(run func(ctx context.Context, req *servicejobs.JobClaimRequest, opts ...grpc.CallOption)) *MockClient_JobClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobClaimRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobClaimRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JobClaim_Call) Return(v *servicejobs.JobClaimResponse, err error) *MockClient_JobClaim_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JobClaim_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.JobClaimRequest, opts ...grpc.CallOption) (*servicejobs.JobClaimResponse, error)) *MockClient_JobClaim_Call {
	_c.Call.Return(run)
	return _c
}

// JobEnqueue provides a mock function for the type MockClient
func (_mock *MockClient) JobEnqueue(ctx context.Context, req *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobEnqueue")
	}

	var r0 *servicejobs.JobEnqueueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) *servicejobs.JobEnqueueResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobEnqueueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobEnqueueRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JobEnqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobEnqueue'
type MockClient_JobEnqueue_Call struct {
	*mock.Call
}

// JobEnqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.JobEnqueueRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JobEnqueue(ctx any, req any, opts ...any) *MockClient_JobEnqueue_Call {
	return &MockClient_JobEnqueue_Call{Call: _e.mock.On("JobEnqueue",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_JobEnqueue_Call) Run(run func(ctx context.Context, req *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption)) *MockClient_JobEnqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobEnqueueRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobEnqueueRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JobEnqueue_Call) Return(v *servicejobs.JobEnqueueResponse, err error) *MockClient_JobEnqueue_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JobEnqueue_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.JobEnqueueRequest, opts ...grpc.CallOption) (*servicejobs.JobEnqueueResponse, error)) *MockClient_JobEnqueue_Call {
	_c.Call.Return(run)
	return _c
}

// JobGet provides a mock function for the type MockClient
func (_mock *MockClient) JobGet(ctx context.Context, req *servicejobs.JobGetRequest, opts ...grpc.CallOption) (*servicejobs.JobGetResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobGet")
	}

	var r0 *servicejobs.JobGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) (*servicejobs.JobGetResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) *servicejobs.JobGetResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobGetRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JobGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobGet'
type MockClient_JobGet_Call struct {
	*mock.Call
}

// JobGet is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.JobGetRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JobGet(ctx any, req any, opts ...any) *MockClient_JobGet_Call {
	return &MockClient_JobGet_Call{Call: _e.mock.On("JobGet",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_JobGet_Call) Run(run func(ctx context.Context, req *servicejobs.JobGetRequest, opts ...grpc.CallOption)) *MockClient_JobGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobGetRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobGetRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JobGet_Call) Return(v *servicejobs.JobGetResponse, err error) *MockClient_JobGet_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JobGet_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.JobGetRequest, opts ...grpc.CallOption) (*servicejobs.JobGetResponse, error)) *MockClient_JobGet_Call {
	_c.Call.Return(run)
	return _c
}

// JobSettle provides a mock function for the type MockClient
func (_mock *MockClient) JobSettle(ctx context.Context, req *servicejobs.JobSettleRequest, opts ...grpc.CallOption) (*servicejobs.JobSettleResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobSettle")
	}

	var r0 *servicejobs.JobSettleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) (*servicejobs.JobSettleResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) *servicejobs.JobSettleResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.JobSettleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobSettleRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JobSettle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobSettle'
type MockClient_JobSettle_Call struct {
	*mock.Call
}

// JobSettle is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.JobSettleRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JobSettle(ctx any, req any, opts ...any) *MockClient_JobSettle_Call {
	return &MockClient_JobSettle_Call{Call: _e.mock.On("JobSettle",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_JobSettle_Call) Run(run func(ctx context.Context, req *servicejobs.JobSettleRequest, opts ...grpc.CallOption)) *MockClient_JobSettle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobSettleRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JobSettle_Call) Return(v *servicejobs.JobSettleResponse, err error) *MockClient_JobSettle_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JobSettle_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.JobSettleRequest, opts ...grpc.CallOption) (*servicejobs.JobSettleResponse, error)) *MockClient_JobSettle_Call {
	_c.Call.Return(run)
	return _c
}

// JobWatch provides a mock function for the type MockClient
func (_mock *MockClient) JobWatch(ctx context.Context, req *servicejobs.JobWatchRequest, opts ...grpc.CallOption) (servicejobs.JobWatchClient, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JobWatch")
	}

	var r0 servicejobs.JobWatchClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobWatchRequest, ...grpc.CallOption) (servicejobs.JobWatchClient, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.JobWatchRequest, ...grpc.CallOption) servicejobs.JobWatchClient); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(servicejobs.JobWatchClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.JobWatchRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JobWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobWatch'
type MockClient_JobWatch_Call struct {
	*mock.Call
}

// JobWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.JobWatchRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) JobWatch(ctx any, req any, opts ...any) *MockClient_JobWatch_Call {
	return &MockClient_JobWatch_Call{Call: _e.mock.On("JobWatch",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_JobWatch_Call) Run(run func(ctx context.Context, req *servicejobs.JobWatchRequest, opts ...grpc.CallOption)) *MockClient_JobWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.JobWatchRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.JobWatchRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_JobWatch_Call) Return(v servicejobs.JobWatchClient, err error) *MockClient_JobWatch_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_JobWatch_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.JobWatchRequest, opts ...grpc.CallOption) (servicejobs.JobWatchClient, error)) *MockClient_JobWatch_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockClient
func (_mock *MockClient) Status(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption) (*servicejobs.StatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *servicejobs.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) (*servicejobs.StatusResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) *servicejobs.StatusResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicejobs.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *servicejobs.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - req *servicejobs.StatusRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) Status(ctx any, req any, opts ...any) *MockClient_Status_Call {
	return &MockClient_Status_Call{Call: _e.mock.On("Status",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_Status_Call) Run(run func(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption)) *MockClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *servicejobs.StatusRequest
		if args[1] != nil {
			arg1 = args[1].(*servicejobs.StatusRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_Status_Call) Return(v *servicejobs.StatusResponse, err error) *MockClient_Status_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockClient_Status_Call) RunAndReturn(run func(ctx context.Context, req *servicejobs.StatusRequest, opts ...grpc.CallOption) (*servicejobs.StatusResponse, error)) *MockClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// UnaryEcho provides a mock function for the type MockClient
func (_mock *MockClient) UnaryEcho(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnaryEcho")
	}

	var r0 *golibproto.UnaryEchoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) *golibproto.UnaryEchoResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golibproto.UnaryEchoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *golibproto.UnaryEchoRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_UnaryEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnaryEcho'
type MockClient_UnaryEcho_Call struct {
	*mock.Call
}

// UnaryEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - req *golibproto.UnaryEchoRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) UnaryEcho(ctx any, req any, opts ...any) *MockClient_UnaryEcho_Call {
	return &MockClient_UnaryEcho_Call{Call: _e.mock.On("UnaryEcho",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *MockClient_UnaryEcho_Call) Run(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption)) *MockClient_UnaryEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *golibproto.UnaryEchoRequest
		if args[1] != nil {
			arg1 = args[1].(*golibproto.UnaryEchoRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_UnaryEcho_Call) Return(unaryEchoResponse *golibproto.UnaryEchoResponse, err error) *MockClient_UnaryEcho_Call {
	_c.Call.Return(unaryEchoResponse, err)
	return _c
}

func (_c *MockClient_UnaryEcho_Call) RunAndReturn(run func(ctx context.Context, req *golibproto.UnaryEchoRequest, opts ...grpc.CallOption) (*golibproto.UnaryEchoResponse, error)) *MockClient_UnaryEcho_Call {
	_c.Call.Return(run)
	return _c
}
