// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus is where a job sits in its lifecycle.
type JobStatus int32

const (
	// JOB_STATUS_UNSPECIFIED means the status was not set. It is never a value the queue stores.
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	// JOB_STATUS_PENDING means the job is waiting to be claimed.
	JobStatus_JOB_STATUS_PENDING JobStatus = 1
	// JOB_STATUS_CLAIMED means a worker holds a lease on the job and is running it.
	JobStatus_JOB_STATUS_CLAIMED JobStatus = 2
	// JOB_STATUS_SUCCEEDED means the job's handler returned a result.
	JobStatus_JOB_STATUS_SUCCEEDED JobStatus = 3
	// JOB_STATUS_FAILED means the job's handler failed with no attempt left to retry.
	JobStatus_JOB_STATUS_FAILED JobStatus = 4
	// JOB_STATUS_ABANDONED means the reaper settled the job because its lease expired with no attempt
	// remaining — the worker running it died mid-run.
	JobStatus_JOB_STATUS_ABANDONED JobStatus = 5
	// JOB_STATUS_CANCELLED means the job was settled on the owner's request rather than by running it.
	JobStatus_JOB_STATUS_CANCELLED JobStatus = 6
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_CLAIMED",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_ABANDONED",
		6: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_CLAIMED":     2,
		"JOB_STATUS_SUCCEEDED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_ABANDONED":   5,
		"JOB_STATUS_CANCELLED":   6,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

// A Job is one unit of asynchronous work as the queue exposes it. The queue never interprets its
// payload, result or error — they are opaque JSON bytes the owning service reads.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Kind names the handler that runs the job. Opaque to the queue.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Payload is the caller-supplied input, as JSON bytes.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// OwnerID is the user the job acts for, formatted as a UUID.
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Status is where the job sits in its lifecycle.
	Status JobStatus `protobuf:"varint,5,opt,name=status,proto3,enum=JobStatus" json:"status,omitempty"`
	// Attempt counts runs already begun.
	Attempt int32 `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// MaxAttempts caps the value Attempt may reach.
	MaxAttempts int32 `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Result is the handler's output on success, as JSON bytes. Empty until the job succeeds.
	Result []byte `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	// Error is the structured failure on a terminal failure, as JSON bytes. Empty otherwise.
	Error []byte `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// ProviderCallID is a third party's identifier for the operation this job started. Empty until a
	// provider call records one.
	ProviderCallId string `protobuf:"bytes,10,opt,name=provider_call_id,json=providerCallId,proto3" json:"provider_call_id,omitempty"`
	// Creation timestamp, formatted as RFC 3339.
	CreatedAt string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of the most recent update, formatted as RFC 3339.
	UpdatedAt string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp the job reached a terminal status, formatted as RFC 3339. Empty until it settles.
	SettledAt string `protobuf:"bytes,13,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	// Timestamp the settled job may be purged, formatted as RFC 3339. Empty until it settles.
	ExpiresAt     string `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Job) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Job) GetProviderCallId() string {
	if x != nil {
		return x.ProviderCallId
	}
	return ""
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Job) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Job) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

func (x *Job) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\"\x93\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\"\n" +
	"\x06status\x18\x05 \x01(\x0e2\n" +
	".JobStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x05R\vmaxAttempts\x12\x16\n" +
	"\x06result\x18\b \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\t \x01(\fR\x05error\x12(\n" +
	"\x10provider_call_id\x18\n" +
	" \x01(\tR\x0eproviderCallId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\r \x01(\tR\tsettledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\tR\texpiresAt*\xbc\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_CLAIMED\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_ABANDONED\x10\x05\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x06BQB\bJobProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_job_proto_goTypes = []any{
	(JobStatus)(0), // 0: JobStatus
	(*Job)(nil),    // 1: Job
}
var file_job_proto_depIdxs = []int32{
	0, // 0: Job.status:type_name -> JobStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		EnumInfos:         file_job_proto_enumTypes,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
