// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_watch.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobWatchRequest identifies the job to watch and the owner it must belong to.
type JobWatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the job to watch, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID scopes the watch, formatted as a UUID. A job owned by anyone else reports not-found.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobWatchRequest) Reset() {
	*x = JobWatchRequest{}
	mi := &file_job_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobWatchRequest) ProtoMessage() {}

func (x *JobWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobWatchRequest.ProtoReflect.Descriptor instead.
func (*JobWatchRequest) Descriptor() ([]byte, []int) {
	return file_job_watch_proto_rawDescGZIP(), []int{0}
}

func (x *JobWatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobWatchRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// JobWatchResponse carries one snapshot of the watched job. One is sent on subscribe and one on each
// change until the job is terminal.
type JobWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobWatchResponse) Reset() {
	*x = JobWatchResponse{}
	mi := &file_job_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobWatchResponse) ProtoMessage() {}

func (x *JobWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobWatchResponse.ProtoReflect.Descriptor instead.
func (*JobWatchResponse) Descriptor() ([]byte, []int) {
	return file_job_watch_proto_rawDescGZIP(), []int{1}
}

func (x *JobWatchResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_job_watch_proto protoreflect.FileDescriptor

const file_job_watch_proto_rawDesc = "" +
	"\n" +
	"\x0fjob_watch.proto\x1a\tjob.proto\"<\n" +
	"\x0fJobWatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"*\n" +
	"\x10JobWatchResponse\x12\x16\n" +
	"\x03job\x18\x01 \x01(\v2\x04.JobR\x03job2D\n" +
	"\x0fJobWatchService\x121\n" +
	"\bJobWatch\x12\x10.JobWatchRequest\x1a\x11.JobWatchResponse0\x01BVB\rJobWatchProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_watch_proto_rawDescOnce sync.Once
	file_job_watch_proto_rawDescData []byte
)

func file_job_watch_proto_rawDescGZIP() []byte {
	file_job_watch_proto_rawDescOnce.Do(func() {
		file_job_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_watch_proto_rawDesc), len(file_job_watch_proto_rawDesc)))
	})
	return file_job_watch_proto_rawDescData
}

var file_job_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_watch_proto_goTypes = []any{
	(*JobWatchRequest)(nil),  // 0: JobWatchRequest
	(*JobWatchResponse)(nil), // 1: JobWatchResponse
	(*Job)(nil),              // 2: Job
}
var file_job_watch_proto_depIdxs = []int32{
	2, // 0: JobWatchResponse.job:type_name -> Job
	0, // 1: JobWatchService.JobWatch:input_type -> JobWatchRequest
	1, // 2: JobWatchService.JobWatch:output_type -> JobWatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_watch_proto_init() }
func file_job_watch_proto_init() {
	if File_job_watch_proto != nil {
		return
	}
	file_job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_watch_proto_rawDesc), len(file_job_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_watch_proto_goTypes,
		DependencyIndexes: file_job_watch_proto_depIdxs,
		MessageInfos:      file_job_watch_proto_msgTypes,
	}.Build()
	File_job_watch_proto = out.File
	file_job_watch_proto_goTypes = nil
	file_job_watch_proto_depIdxs = nil
}
