// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_settle.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobSettleRequest reports the outcome of a run. Exactly one of the outcome fields is set: a success
// carrying the result, or a failure.
type JobSettleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the job to settle, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// WorkerID must hold the claim on the job. A worker cannot settle work it does not hold.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Outcome is the result on success or the failure otherwise.
	//
	// Types that are valid to be assigned to Outcome:
	//
	//	*JobSettleRequest_Result
	//	*JobSettleRequest_Failure
	Outcome       isJobSettleRequest_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSettleRequest) Reset() {
	*x = JobSettleRequest{}
	mi := &file_job_settle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSettleRequest) ProtoMessage() {}

func (x *JobSettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_settle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSettleRequest.ProtoReflect.Descriptor instead.
func (*JobSettleRequest) Descriptor() ([]byte, []int) {
	return file_job_settle_proto_rawDescGZIP(), []int{0}
}

func (x *JobSettleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobSettleRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobSettleRequest) GetOutcome() isJobSettleRequest_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *JobSettleRequest) GetResult() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*JobSettleRequest_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *JobSettleRequest) GetFailure() *JobFailure {
	if x != nil {
		if x, ok := x.Outcome.(*JobSettleRequest_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isJobSettleRequest_Outcome interface {
	isJobSettleRequest_Outcome()
}

type JobSettleRequest_Result struct {
	// Result is the handler's output on success, as JSON bytes.
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type JobSettleRequest_Failure struct {
	// Failure describes a failed run.
	Failure *JobFailure `protobuf:"bytes,4,opt,name=failure,proto3,oneof"`
}

func (*JobSettleRequest_Result) isJobSettleRequest_Outcome() {}

func (*JobSettleRequest_Failure) isJobSettleRequest_Outcome() {}

// JobFailure is the outcome of a failed run.
type JobFailure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error is the structured failure recorded on the job, as JSON bytes.
	Error []byte `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Retryable marks a failure the substrate may retry while attempts remain. A worker that leaves it
	// false gets a single attempt, the right default for a priced call.
	Retryable     bool `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailure) Reset() {
	*x = JobFailure{}
	mi := &file_job_settle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailure) ProtoMessage() {}

func (x *JobFailure) ProtoReflect() protoreflect.Message {
	mi := &file_job_settle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailure.ProtoReflect.Descriptor instead.
func (*JobFailure) Descriptor() ([]byte, []int) {
	return file_job_settle_proto_rawDescGZIP(), []int{1}
}

func (x *JobFailure) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *JobFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// JobSettleResponse returns the job after the transition — terminal on success or a spent failure,
// pending again when a retryable failure had an attempt left.
type JobSettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSettleResponse) Reset() {
	*x = JobSettleResponse{}
	mi := &file_job_settle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSettleResponse) ProtoMessage() {}

func (x *JobSettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_settle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSettleResponse.ProtoReflect.Descriptor instead.
func (*JobSettleResponse) Descriptor() ([]byte, []int) {
	return file_job_settle_proto_rawDescGZIP(), []int{2}
}

func (x *JobSettleResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_job_settle_proto protoreflect.FileDescriptor

const file_job_settle_proto_rawDesc = "" +
	"\n" +
	"\x10job_settle.proto\x1a\tjob.proto\"\x8d\x01\n" +
	"\x10JobSettleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\x06result\x18\x03 \x01(\fH\x00R\x06result\x12'\n" +
	"\afailure\x18\x04 \x01(\v2\v.JobFailureH\x00R\afailureB\t\n" +
	"\aoutcome\"@\n" +
	"\n" +
	"JobFailure\x12\x14\n" +
	"\x05error\x18\x01 \x01(\fR\x05error\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\"+\n" +
	"\x11JobSettleResponse\x12\x16\n" +
	"\x03job\x18\x01 \x01(\v2\x04.JobR\x03job2F\n" +
	"\x10JobSettleService\x122\n" +
	"\tJobSettle\x12\x11.JobSettleRequest\x1a\x12.JobSettleResponseBWB\x0eJobSettleProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_settle_proto_rawDescOnce sync.Once
	file_job_settle_proto_rawDescData []byte
)

func file_job_settle_proto_rawDescGZIP() []byte {
	file_job_settle_proto_rawDescOnce.Do(func() {
		file_job_settle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_settle_proto_rawDesc), len(file_job_settle_proto_rawDesc)))
	})
	return file_job_settle_proto_rawDescData
}

var file_job_settle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_job_settle_proto_goTypes = []any{
	(*JobSettleRequest)(nil),  // 0: JobSettleRequest
	(*JobFailure)(nil),        // 1: JobFailure
	(*JobSettleResponse)(nil), // 2: JobSettleResponse
	(*Job)(nil),               // 3: Job
}
var file_job_settle_proto_depIdxs = []int32{
	1, // 0: JobSettleRequest.failure:type_name -> JobFailure
	3, // 1: JobSettleResponse.job:type_name -> Job
	0, // 2: JobSettleService.JobSettle:input_type -> JobSettleRequest
	2, // 3: JobSettleService.JobSettle:output_type -> JobSettleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_job_settle_proto_init() }
func file_job_settle_proto_init() {
	if File_job_settle_proto != nil {
		return
	}
	file_job_proto_init()
	file_job_settle_proto_msgTypes[0].OneofWrappers = []any{
		(*JobSettleRequest_Result)(nil),
		(*JobSettleRequest_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_settle_proto_rawDesc), len(file_job_settle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_settle_proto_goTypes,
		DependencyIndexes: file_job_settle_proto_depIdxs,
		MessageInfos:      file_job_settle_proto_msgTypes,
	}.Build()
	File_job_settle_proto = out.File
	file_job_settle_proto_goTypes = nil
	file_job_settle_proto_depIdxs = nil
}
