// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_claim.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobClaimRequest carries what a worker needs to claim work.
type JobClaimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kinds are the handler kinds this worker serves. A worker that names none claims nothing.
	Kinds []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	// WorkerID is recorded on each claimed job so a stranded claim can be traced.
	WorkerId string `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Limit caps how many jobs one claim takes.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// LeaseSeconds is the visibility timeout: how long the claim holds before the reaper may recover
	// the job. Added to the database clock, so worker clock skew never enters the lease.
	LeaseSeconds  int32 `protobuf:"varint,4,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobClaimRequest) Reset() {
	*x = JobClaimRequest{}
	mi := &file_job_claim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobClaimRequest) ProtoMessage() {}

func (x *JobClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_claim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobClaimRequest.ProtoReflect.Descriptor instead.
func (*JobClaimRequest) Descriptor() ([]byte, []int) {
	return file_job_claim_proto_rawDescGZIP(), []int{0}
}

func (x *JobClaimRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *JobClaimRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobClaimRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *JobClaimRequest) GetLeaseSeconds() int32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

// JobClaimResponse returns the claimed batch, empty when nothing was available.
type JobClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobClaimResponse) Reset() {
	*x = JobClaimResponse{}
	mi := &file_job_claim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobClaimResponse) ProtoMessage() {}

func (x *JobClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_claim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobClaimResponse.ProtoReflect.Descriptor instead.
func (*JobClaimResponse) Descriptor() ([]byte, []int) {
	return file_job_claim_proto_rawDescGZIP(), []int{1}
}

func (x *JobClaimResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_job_claim_proto protoreflect.FileDescriptor

const file_job_claim_proto_rawDesc = "" +
	"\n" +
	"\x0fjob_claim.proto\x1a\tjob.proto\"\x7f\n" +
	"\x0fJobClaimRequest\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12#\n" +
	"\rlease_seconds\x18\x04 \x01(\x05R\fleaseSeconds\",\n" +
	"\x10JobClaimResponse\x12\x18\n" +
	"\x04jobs\x18\x01 \x03(\v2\x04.JobR\x04jobs2B\n" +
	"\x0fJobClaimService\x12/\n" +
	"\bJobClaim\x12\x10.JobClaimRequest\x1a\x11.JobClaimResponseBVB\rJobClaimProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_claim_proto_rawDescOnce sync.Once
	file_job_claim_proto_rawDescData []byte
)

func file_job_claim_proto_rawDescGZIP() []byte {
	file_job_claim_proto_rawDescOnce.Do(func() {
		file_job_claim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_claim_proto_rawDesc), len(file_job_claim_proto_rawDesc)))
	})
	return file_job_claim_proto_rawDescData
}

var file_job_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_claim_proto_goTypes = []any{
	(*JobClaimRequest)(nil),  // 0: JobClaimRequest
	(*JobClaimResponse)(nil), // 1: JobClaimResponse
	(*Job)(nil),              // 2: Job
}
var file_job_claim_proto_depIdxs = []int32{
	2, // 0: JobClaimResponse.jobs:type_name -> Job
	0, // 1: JobClaimService.JobClaim:input_type -> JobClaimRequest
	1, // 2: JobClaimService.JobClaim:output_type -> JobClaimResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_claim_proto_init() }
func file_job_claim_proto_init() {
	if File_job_claim_proto != nil {
		return
	}
	file_job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_claim_proto_rawDesc), len(file_job_claim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_claim_proto_goTypes,
		DependencyIndexes: file_job_claim_proto_depIdxs,
		MessageInfos:      file_job_claim_proto_msgTypes,
	}.Build()
	File_job_claim_proto = out.File
	file_job_claim_proto_goTypes = nil
	file_job_claim_proto_depIdxs = nil
}
