// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: job_enqueue.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobEnqueueService_JobEnqueue_FullMethodName = "/JobEnqueueService/JobEnqueue"
)

// JobEnqueueServiceClient is the client API for JobEnqueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobEnqueueService records a unit of asynchronous work, deduplicating on the idempotency key.
type JobEnqueueServiceClient interface {
	JobEnqueue(ctx context.Context, in *JobEnqueueRequest, opts ...grpc.CallOption) (*JobEnqueueResponse, error)
}

type jobEnqueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobEnqueueServiceClient(cc grpc.ClientConnInterface) JobEnqueueServiceClient {
	return &jobEnqueueServiceClient{cc}
}

func (c *jobEnqueueServiceClient) JobEnqueue(ctx context.Context, in *JobEnqueueRequest, opts ...grpc.CallOption) (*JobEnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobEnqueueResponse)
	err := c.cc.Invoke(ctx, JobEnqueueService_JobEnqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobEnqueueServiceServer is the server API for JobEnqueueService service.
// All implementations must embed UnimplementedJobEnqueueServiceServer
// for forward compatibility.
//
// JobEnqueueService records a unit of asynchronous work, deduplicating on the idempotency key.
type JobEnqueueServiceServer interface {
	JobEnqueue(context.Context, *JobEnqueueRequest) (*JobEnqueueResponse, error)
	mustEmbedUnimplementedJobEnqueueServiceServer()
}

// UnimplementedJobEnqueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobEnqueueServiceServer struct{}

func (UnimplementedJobEnqueueServiceServer) JobEnqueue(context.Context, *JobEnqueueRequest) (*JobEnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobEnqueue not implemented")
}
func (UnimplementedJobEnqueueServiceServer) mustEmbedUnimplementedJobEnqueueServiceServer() {}
func (UnimplementedJobEnqueueServiceServer) testEmbeddedByValue()                           {}

// UnsafeJobEnqueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobEnqueueServiceServer will
// result in compilation errors.
type UnsafeJobEnqueueServiceServer interface {
	mustEmbedUnimplementedJobEnqueueServiceServer()
}

func RegisterJobEnqueueServiceServer(s grpc.ServiceRegistrar, srv JobEnqueueServiceServer) {
	// If the following call panics, it indicates UnimplementedJobEnqueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobEnqueueService_ServiceDesc, srv)
}

func _JobEnqueueService_JobEnqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobEnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobEnqueueServiceServer).JobEnqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobEnqueueService_JobEnqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobEnqueueServiceServer).JobEnqueue(ctx, req.(*JobEnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobEnqueueService_ServiceDesc is the grpc.ServiceDesc for JobEnqueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobEnqueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobEnqueueService",
	HandlerType: (*JobEnqueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobEnqueue",
			Handler:    _JobEnqueueService_JobEnqueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_enqueue.proto",
}
