// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: job_claim.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobClaimService_JobClaim_FullMethodName = "/JobClaimService/JobClaim"
)

// JobClaimServiceClient is the client API for JobClaimService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobClaimService takes a batch of pending jobs for a worker to run. Concurrent claims never contend:
// each takes a disjoint batch and neither blocks the other.
type JobClaimServiceClient interface {
	JobClaim(ctx context.Context, in *JobClaimRequest, opts ...grpc.CallOption) (*JobClaimResponse, error)
}

type jobClaimServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClaimServiceClient(cc grpc.ClientConnInterface) JobClaimServiceClient {
	return &jobClaimServiceClient{cc}
}

func (c *jobClaimServiceClient) JobClaim(ctx context.Context, in *JobClaimRequest, opts ...grpc.CallOption) (*JobClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobClaimResponse)
	err := c.cc.Invoke(ctx, JobClaimService_JobClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobClaimServiceServer is the server API for JobClaimService service.
// All implementations must embed UnimplementedJobClaimServiceServer
// for forward compatibility.
//
// JobClaimService takes a batch of pending jobs for a worker to run. Concurrent claims never contend:
// each takes a disjoint batch and neither blocks the other.
type JobClaimServiceServer interface {
	JobClaim(context.Context, *JobClaimRequest) (*JobClaimResponse, error)
	mustEmbedUnimplementedJobClaimServiceServer()
}

// UnimplementedJobClaimServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobClaimServiceServer struct{}

func (UnimplementedJobClaimServiceServer) JobClaim(context.Context, *JobClaimRequest) (*JobClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobClaim not implemented")
}
func (UnimplementedJobClaimServiceServer) mustEmbedUnimplementedJobClaimServiceServer() {}
func (UnimplementedJobClaimServiceServer) testEmbeddedByValue()                         {}

// UnsafeJobClaimServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobClaimServiceServer will
// result in compilation errors.
type UnsafeJobClaimServiceServer interface {
	mustEmbedUnimplementedJobClaimServiceServer()
}

func RegisterJobClaimServiceServer(s grpc.ServiceRegistrar, srv JobClaimServiceServer) {
	// If the following call panics, it indicates UnimplementedJobClaimServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobClaimService_ServiceDesc, srv)
}

func _JobClaimService_JobClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobClaimServiceServer).JobClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobClaimService_JobClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobClaimServiceServer).JobClaim(ctx, req.(*JobClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobClaimService_ServiceDesc is the grpc.ServiceDesc for JobClaimService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobClaimService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobClaimService",
	HandlerType: (*JobClaimServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobClaim",
			Handler:    _JobClaimService_JobClaim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_claim.proto",
}
