// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: job_watch.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobWatchService_JobWatch_FullMethodName = "/JobWatchService/JobWatch"
)

// JobWatchServiceClient is the client API for JobWatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobWatchService streams a job's state to a caller waiting on its outcome. The stream is resumable
// by construction: a caller that reconnects calls it again, and the server answers from current
// state — the job as it stands now, then each change until it is terminal. There is no cursor and no
// window in which a change can be missed, because the stream reads durable state rather than
// consuming events.
//
// A caller that wants a single answer uses JobGet instead; this is the latency lever for a caller
// that would otherwise poll.
type JobWatchServiceClient interface {
	JobWatch(ctx context.Context, in *JobWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobWatchResponse], error)
}

type jobWatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobWatchServiceClient(cc grpc.ClientConnInterface) JobWatchServiceClient {
	return &jobWatchServiceClient{cc}
}

func (c *jobWatchServiceClient) JobWatch(ctx context.Context, in *JobWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobWatchService_ServiceDesc.Streams[0], JobWatchService_JobWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobWatchRequest, JobWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWatchService_JobWatchClient = grpc.ServerStreamingClient[JobWatchResponse]

// JobWatchServiceServer is the server API for JobWatchService service.
// All implementations must embed UnimplementedJobWatchServiceServer
// for forward compatibility.
//
// JobWatchService streams a job's state to a caller waiting on its outcome. The stream is resumable
// by construction: a caller that reconnects calls it again, and the server answers from current
// state — the job as it stands now, then each change until it is terminal. There is no cursor and no
// window in which a change can be missed, because the stream reads durable state rather than
// consuming events.
//
// A caller that wants a single answer uses JobGet instead; this is the latency lever for a caller
// that would otherwise poll.
type JobWatchServiceServer interface {
	JobWatch(*JobWatchRequest, grpc.ServerStreamingServer[JobWatchResponse]) error
	mustEmbedUnimplementedJobWatchServiceServer()
}

// UnimplementedJobWatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobWatchServiceServer struct{}

func (UnimplementedJobWatchServiceServer) JobWatch(*JobWatchRequest, grpc.ServerStreamingServer[JobWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method JobWatch not implemented")
}
func (UnimplementedJobWatchServiceServer) mustEmbedUnimplementedJobWatchServiceServer() {}
func (UnimplementedJobWatchServiceServer) testEmbeddedByValue()                         {}

// UnsafeJobWatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobWatchServiceServer will
// result in compilation errors.
type UnsafeJobWatchServiceServer interface {
	mustEmbedUnimplementedJobWatchServiceServer()
}

func RegisterJobWatchServiceServer(s grpc.ServiceRegistrar, srv JobWatchServiceServer) {
	// If the following call panics, it indicates UnimplementedJobWatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobWatchService_ServiceDesc, srv)
}

func _JobWatchService_JobWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobWatchServiceServer).JobWatch(m, &grpc.GenericServerStream[JobWatchRequest, JobWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobWatchService_JobWatchServer = grpc.ServerStreamingServer[JobWatchResponse]

// JobWatchService_ServiceDesc is the grpc.ServiceDesc for JobWatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobWatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobWatchService",
	HandlerType: (*JobWatchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JobWatch",
			Handler:       _JobWatchService_JobWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job_watch.proto",
}
