// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: job_get.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobGetService_JobGet_FullMethodName = "/JobGetService/JobGet"
)

// JobGetServiceClient is the client API for JobGetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobGetService reads one of an owner's jobs by its id. A job owned by anyone else reports not-found,
// so the read cannot be used to learn whether a job id exists.
type JobGetServiceClient interface {
	JobGet(ctx context.Context, in *JobGetRequest, opts ...grpc.CallOption) (*JobGetResponse, error)
}

type jobGetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobGetServiceClient(cc grpc.ClientConnInterface) JobGetServiceClient {
	return &jobGetServiceClient{cc}
}

func (c *jobGetServiceClient) JobGet(ctx context.Context, in *JobGetRequest, opts ...grpc.CallOption) (*JobGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobGetResponse)
	err := c.cc.Invoke(ctx, JobGetService_JobGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobGetServiceServer is the server API for JobGetService service.
// All implementations must embed UnimplementedJobGetServiceServer
// for forward compatibility.
//
// JobGetService reads one of an owner's jobs by its id. A job owned by anyone else reports not-found,
// so the read cannot be used to learn whether a job id exists.
type JobGetServiceServer interface {
	JobGet(context.Context, *JobGetRequest) (*JobGetResponse, error)
	mustEmbedUnimplementedJobGetServiceServer()
}

// UnimplementedJobGetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobGetServiceServer struct{}

func (UnimplementedJobGetServiceServer) JobGet(context.Context, *JobGetRequest) (*JobGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobGet not implemented")
}
func (UnimplementedJobGetServiceServer) mustEmbedUnimplementedJobGetServiceServer() {}
func (UnimplementedJobGetServiceServer) testEmbeddedByValue()                       {}

// UnsafeJobGetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobGetServiceServer will
// result in compilation errors.
type UnsafeJobGetServiceServer interface {
	mustEmbedUnimplementedJobGetServiceServer()
}

func RegisterJobGetServiceServer(s grpc.ServiceRegistrar, srv JobGetServiceServer) {
	// If the following call panics, it indicates UnimplementedJobGetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobGetService_ServiceDesc, srv)
}

func _JobGetService_JobGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobGetServiceServer).JobGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobGetService_JobGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobGetServiceServer).JobGet(ctx, req.(*JobGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobGetService_ServiceDesc is the grpc.ServiceDesc for JobGetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobGetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobGetService",
	HandlerType: (*JobGetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobGet",
			Handler:    _JobGetService_JobGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_get.proto",
}
