// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_enqueue.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobEnqueueRequest carries a new job. The server mints the id and the timestamps.
type JobEnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind names the handler that will run the job. Required.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Payload is the handler's opaque input, as JSON bytes.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// OwnerID is the user the job acts for, formatted as a UUID. Supplied by the calling service.
	OwnerId string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// IdempotencyKey deduplicates repeat submissions within one owner and kind. Unset skips
	// deduplication; a value reused with a different payload is a conflict, not a replay.
	IdempotencyKey *string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	// MaxAttempts caps the runs the job gets. Zero means one, the right floor for a priced call.
	MaxAttempts   int32 `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEnqueueRequest) Reset() {
	*x = JobEnqueueRequest{}
	mi := &file_job_enqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnqueueRequest) ProtoMessage() {}

func (x *JobEnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_enqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnqueueRequest.ProtoReflect.Descriptor instead.
func (*JobEnqueueRequest) Descriptor() ([]byte, []int) {
	return file_job_enqueue_proto_rawDescGZIP(), []int{0}
}

func (x *JobEnqueueRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *JobEnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobEnqueueRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *JobEnqueueRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *JobEnqueueRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

// JobEnqueueResponse returns the recorded job and whether this call created it.
type JobEnqueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job is the recorded job — the newly created one, or the existing one on an idempotent replay.
	Job *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	// Created is false when an existing job was returned under the same idempotency key, so a caller
	// retrying a request attaches to the work already in flight instead of paying for a second one.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEnqueueResponse) Reset() {
	*x = JobEnqueueResponse{}
	mi := &file_job_enqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnqueueResponse) ProtoMessage() {}

func (x *JobEnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_enqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnqueueResponse.ProtoReflect.Descriptor instead.
func (*JobEnqueueResponse) Descriptor() ([]byte, []int) {
	return file_job_enqueue_proto_rawDescGZIP(), []int{1}
}

func (x *JobEnqueueResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobEnqueueResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_job_enqueue_proto protoreflect.FileDescriptor

const file_job_enqueue_proto_rawDesc = "" +
	"\n" +
	"\x11job_enqueue.proto\x1a\tjob.proto\"\xc1\x01\n" +
	"\x11JobEnqueueRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttemptsB\x12\n" +
	"\x10_idempotency_key\"F\n" +
	"\x12JobEnqueueResponse\x12\x16\n" +
	"\x03job\x18\x01 \x01(\v2\x04.JobR\x03job\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated2J\n" +
	"\x11JobEnqueueService\x125\n" +
	"\n" +
	"JobEnqueue\x12\x12.JobEnqueueRequest\x1a\x13.JobEnqueueResponseBXB\x0fJobEnqueueProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_enqueue_proto_rawDescOnce sync.Once
	file_job_enqueue_proto_rawDescData []byte
)

func file_job_enqueue_proto_rawDescGZIP() []byte {
	file_job_enqueue_proto_rawDescOnce.Do(func() {
		file_job_enqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_enqueue_proto_rawDesc), len(file_job_enqueue_proto_rawDesc)))
	})
	return file_job_enqueue_proto_rawDescData
}

var file_job_enqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_enqueue_proto_goTypes = []any{
	(*JobEnqueueRequest)(nil),  // 0: JobEnqueueRequest
	(*JobEnqueueResponse)(nil), // 1: JobEnqueueResponse
	(*Job)(nil),                // 2: Job
}
var file_job_enqueue_proto_depIdxs = []int32{
	2, // 0: JobEnqueueResponse.job:type_name -> Job
	0, // 1: JobEnqueueService.JobEnqueue:input_type -> JobEnqueueRequest
	1, // 2: JobEnqueueService.JobEnqueue:output_type -> JobEnqueueResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_enqueue_proto_init() }
func file_job_enqueue_proto_init() {
	if File_job_enqueue_proto != nil {
		return
	}
	file_job_proto_init()
	file_job_enqueue_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_enqueue_proto_rawDesc), len(file_job_enqueue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_enqueue_proto_goTypes,
		DependencyIndexes: file_job_enqueue_proto_depIdxs,
		MessageInfos:      file_job_enqueue_proto_msgTypes,
	}.Build()
	File_job_enqueue_proto = out.File
	file_job_enqueue_proto_goTypes = nil
	file_job_enqueue_proto_depIdxs = nil
}
