// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job_get.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobGetRequest identifies the job to read and the owner it must belong to.
type JobGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the job to read, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID scopes the read, formatted as a UUID. A job owned by anyone else reports not-found.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGetRequest) Reset() {
	*x = JobGetRequest{}
	mi := &file_job_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGetRequest) ProtoMessage() {}

func (x *JobGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGetRequest.ProtoReflect.Descriptor instead.
func (*JobGetRequest) Descriptor() ([]byte, []int) {
	return file_job_get_proto_rawDescGZIP(), []int{0}
}

func (x *JobGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobGetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// JobGetResponse returns the job.
type JobGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobGetResponse) Reset() {
	*x = JobGetResponse{}
	mi := &file_job_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGetResponse) ProtoMessage() {}

func (x *JobGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobGetResponse.ProtoReflect.Descriptor instead.
func (*JobGetResponse) Descriptor() ([]byte, []int) {
	return file_job_get_proto_rawDescGZIP(), []int{1}
}

func (x *JobGetResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_job_get_proto protoreflect.FileDescriptor

const file_job_get_proto_rawDesc = "" +
	"\n" +
	"\rjob_get.proto\x1a\tjob.proto\":\n" +
	"\rJobGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"(\n" +
	"\x0eJobGetResponse\x12\x16\n" +
	"\x03job\x18\x01 \x01(\v2\x04.JobR\x03job2:\n" +
	"\rJobGetService\x12)\n" +
	"\x06JobGet\x12\x0e.JobGetRequest\x1a\x0f.JobGetResponseBTB\vJobGetProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_job_get_proto_rawDescOnce sync.Once
	file_job_get_proto_rawDescData []byte
)

func file_job_get_proto_rawDescGZIP() []byte {
	file_job_get_proto_rawDescOnce.Do(func() {
		file_job_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_get_proto_rawDesc), len(file_job_get_proto_rawDesc)))
	})
	return file_job_get_proto_rawDescData
}

var file_job_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_get_proto_goTypes = []any{
	(*JobGetRequest)(nil),  // 0: JobGetRequest
	(*JobGetResponse)(nil), // 1: JobGetResponse
	(*Job)(nil),            // 2: Job
}
var file_job_get_proto_depIdxs = []int32{
	2, // 0: JobGetResponse.job:type_name -> Job
	0, // 1: JobGetService.JobGet:input_type -> JobGetRequest
	1, // 2: JobGetService.JobGet:output_type -> JobGetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_job_get_proto_init() }
func file_job_get_proto_init() {
	if File_job_get_proto != nil {
		return
	}
	file_job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_get_proto_rawDesc), len(file_job_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_get_proto_goTypes,
		DependencyIndexes: file_job_get_proto_depIdxs,
		MessageInfos:      file_job_get_proto_msgTypes,
	}.Build()
	File_job_get_proto = out.File
	file_job_get_proto_goTypes = nil
	file_job_get_proto_depIdxs = nil
}
