// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: job_settle.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobSettleService_JobSettle_FullMethodName = "/JobSettleService/JobSettle"
)

// JobSettleServiceClient is the client API for JobSettleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobSettleService records the outcome of a run. A retryable failure folds into settle: there is no
// separate requeue call, so a worker cannot hand back a job it has already reported failed.
type JobSettleServiceClient interface {
	JobSettle(ctx context.Context, in *JobSettleRequest, opts ...grpc.CallOption) (*JobSettleResponse, error)
}

type jobSettleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobSettleServiceClient(cc grpc.ClientConnInterface) JobSettleServiceClient {
	return &jobSettleServiceClient{cc}
}

func (c *jobSettleServiceClient) JobSettle(ctx context.Context, in *JobSettleRequest, opts ...grpc.CallOption) (*JobSettleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobSettleResponse)
	err := c.cc.Invoke(ctx, JobSettleService_JobSettle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobSettleServiceServer is the server API for JobSettleService service.
// All implementations must embed UnimplementedJobSettleServiceServer
// for forward compatibility.
//
// JobSettleService records the outcome of a run. A retryable failure folds into settle: there is no
// separate requeue call, so a worker cannot hand back a job it has already reported failed.
type JobSettleServiceServer interface {
	JobSettle(context.Context, *JobSettleRequest) (*JobSettleResponse, error)
	mustEmbedUnimplementedJobSettleServiceServer()
}

// UnimplementedJobSettleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobSettleServiceServer struct{}

func (UnimplementedJobSettleServiceServer) JobSettle(context.Context, *JobSettleRequest) (*JobSettleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobSettle not implemented")
}
func (UnimplementedJobSettleServiceServer) mustEmbedUnimplementedJobSettleServiceServer() {}
func (UnimplementedJobSettleServiceServer) testEmbeddedByValue()                          {}

// UnsafeJobSettleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobSettleServiceServer will
// result in compilation errors.
type UnsafeJobSettleServiceServer interface {
	mustEmbedUnimplementedJobSettleServiceServer()
}

func RegisterJobSettleServiceServer(s grpc.ServiceRegistrar, srv JobSettleServiceServer) {
	// If the following call panics, it indicates UnimplementedJobSettleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobSettleService_ServiceDesc, srv)
}

func _JobSettleService_JobSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSettleServiceServer).JobSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSettleService_JobSettle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSettleServiceServer).JobSettle(ctx, req.(*JobSettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobSettleService_ServiceDesc is the grpc.ServiceDesc for JobSettleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobSettleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobSettleService",
	HandlerType: (*JobSettleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobSettle",
			Handler:    _JobSettleService_JobSettle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_settle.proto",
}
