// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: status.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DependencyStatus reports whether a single dependency is reachable and serving.
type DependencyStatus int32

const (
	// DEPENDENCY_STATUS_UNSPECIFIED means the status has not yet been assessed, or the assessment failed.
	DependencyStatus_DEPENDENCY_STATUS_UNSPECIFIED DependencyStatus = 0
	// DEPENDENCY_STATUS_UP means the dependency was successfully pinged and should serve normally.
	DependencyStatus_DEPENDENCY_STATUS_UP DependencyStatus = 1
	// DEPENDENCY_STATUS_DOWN means the dependency was reached but did not report a healthy status.
	DependencyStatus_DEPENDENCY_STATUS_DOWN DependencyStatus = 2
)

// Enum value maps for DependencyStatus.
var (
	DependencyStatus_name = map[int32]string{
		0: "DEPENDENCY_STATUS_UNSPECIFIED",
		1: "DEPENDENCY_STATUS_UP",
		2: "DEPENDENCY_STATUS_DOWN",
	}
	DependencyStatus_value = map[string]int32{
		"DEPENDENCY_STATUS_UNSPECIFIED": 0,
		"DEPENDENCY_STATUS_UP":          1,
		"DEPENDENCY_STATUS_DOWN":        2,
	}
)

func (x DependencyStatus) Enum() *DependencyStatus {
	p := new(DependencyStatus)
	*p = x
	return p
}

func (x DependencyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_status_proto_enumTypes[0].Descriptor()
}

func (DependencyStatus) Type() protoreflect.EnumType {
	return &file_status_proto_enumTypes[0]
}

func (x DependencyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyStatus.Descriptor instead.
func (DependencyStatus) EnumDescriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

// DependencyHealth reports the health of a single external dependency.
//
// The message carries the state alone. A dependency health-check error routinely embeds
// internal hostnames, ports, or schema names. The error is recorded on the trace span for
// operators.
type DependencyHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        DependencyStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=DependencyStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyHealth) Reset() {
	*x = DependencyHealth{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyHealth) ProtoMessage() {}

func (x *DependencyHealth) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyHealth.ProtoReflect.Descriptor instead.
func (*DependencyHealth) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *DependencyHealth) GetStatus() DependencyStatus {
	if x != nil {
		return x.Status
	}
	return DependencyStatus_DEPENDENCY_STATUS_UNSPECIFIED
}

// QueueDepth reports the queue's own backlog: how many jobs are due to run and still waiting, and
// how long the oldest of them has waited. Two numbers rather than one — a count alone cannot tell a
// queue absorbing a burst from a stalled one, and the oldest-pending age is what separates them.
type QueueDepth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pending is the number of jobs whose run_at has been reached and that no worker has claimed yet.
	Pending int64 `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	// oldest_pending_age is how long the oldest due-and-unclaimed job has been waiting. Absent when
	// nothing is pending.
	OldestPendingAge *durationpb.Duration `protobuf:"bytes,2,opt,name=oldest_pending_age,json=oldestPendingAge,proto3" json:"oldest_pending_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueDepth) Reset() {
	*x = QueueDepth{}
	mi := &file_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueDepth) ProtoMessage() {}

func (x *QueueDepth) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueDepth.ProtoReflect.Descriptor instead.
func (*QueueDepth) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{1}
}

func (x *QueueDepth) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueDepth) GetOldestPendingAge() *durationpb.Duration {
	if x != nil {
		return x.OldestPendingAge
	}
	return nil
}

// StatusRequest takes no parameters.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{2}
}

// StatusResponse reports the health of each dependency the service relies on, and the queue backlog.
type StatusResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Postgres *DependencyHealth      `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	// queue is the backlog report. Absent when the database is unreachable, since it cannot be
	// measured — postgres reports down in that case.
	Queue         *QueueDepth `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetPostgres() *DependencyHealth {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *StatusResponse) GetQueue() *QueueDepth {
	if x != nil {
		return x.Queue
	}
	return nil
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\x1a\x1egoogle/protobuf/duration.proto\"H\n" +
	"\x10DependencyHealth\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.DependencyStatusR\x06statusJ\x04\b\x02\x10\x03R\x03err\"o\n" +
	"\n" +
	"QueueDepth\x12\x18\n" +
	"\apending\x18\x01 \x01(\x03R\apending\x12G\n" +
	"\x12oldest_pending_age\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10oldestPendingAge\"\x0f\n" +
	"\rStatusRequest\"b\n" +
	"\x0eStatusResponse\x12-\n" +
	"\bpostgres\x18\x01 \x01(\v2\x11.DependencyHealthR\bpostgres\x12!\n" +
	"\x05queue\x18\x02 \x01(\v2\v.QueueDepthR\x05queue*k\n" +
	"\x10DependencyStatus\x12!\n" +
	"\x1dDEPENDENCY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEPENDENCY_STATUS_UP\x10\x01\x12\x1a\n" +
	"\x16DEPENDENCY_STATUS_DOWN\x10\x022:\n" +
	"\rStatusService\x12)\n" +
	"\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponseBTB\vStatusProtoP\x01ZCgithub.com/a-novel/service-jobs/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_status_proto_goTypes = []any{
	(DependencyStatus)(0),       // 0: DependencyStatus
	(*DependencyHealth)(nil),    // 1: DependencyHealth
	(*QueueDepth)(nil),          // 2: QueueDepth
	(*StatusRequest)(nil),       // 3: StatusRequest
	(*StatusResponse)(nil),      // 4: StatusResponse
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_status_proto_depIdxs = []int32{
	0, // 0: DependencyHealth.status:type_name -> DependencyStatus
	5, // 1: QueueDepth.oldest_pending_age:type_name -> google.protobuf.Duration
	1, // 2: StatusResponse.postgres:type_name -> DependencyHealth
	2, // 3: StatusResponse.queue:type_name -> QueueDepth
	3, // 4: StatusService.Status:input_type -> StatusRequest
	4, // 5: StatusService.Status:output_type -> StatusResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		EnumInfos:         file_status_proto_enumTypes,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
