// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-jobs/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemCreateService creates a new instance of MockItemCreateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCreateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCreateService {
	mock := &MockItemCreateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemCreateService is an autogenerated mock type for the ItemCreateService type
type MockItemCreateService struct {
	mock.Mock
}

type MockItemCreateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCreateService) EXPECT() *MockItemCreateService_Expecter {
	return &MockItemCreateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemCreateService
func (_mock *MockItemCreateService) Exec(ctx context.Context, request *core.ItemCreateRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemCreateRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemCreateRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemCreateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemCreateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemCreateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemCreateRequest
func (_e *MockItemCreateService_Expecter) Exec(ctx any, request any) *MockItemCreateService_Exec_Call {
	return &MockItemCreateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemCreateService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemCreateRequest)) *MockItemCreateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemCreateService_Exec_Call) Return(item *core.Item, err error) *MockItemCreateService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemCreateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemCreateRequest) (*core.Item, error)) *MockItemCreateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemDeleteService creates a new instance of MockItemDeleteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemDeleteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemDeleteService {
	mock := &MockItemDeleteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemDeleteService is an autogenerated mock type for the ItemDeleteService type
type MockItemDeleteService struct {
	mock.Mock
}

type MockItemDeleteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemDeleteService) EXPECT() *MockItemDeleteService_Expecter {
	return &MockItemDeleteService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemDeleteService
func (_mock *MockItemDeleteService) Exec(ctx context.Context, request *core.ItemDeleteRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemDeleteRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemDeleteRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemDeleteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemDeleteService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemDeleteService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemDeleteRequest
func (_e *MockItemDeleteService_Expecter) Exec(ctx any, request any) *MockItemDeleteService_Exec_Call {
	return &MockItemDeleteService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemDeleteService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemDeleteRequest)) *MockItemDeleteService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemDeleteService_Exec_Call) Return(item *core.Item, err error) *MockItemDeleteService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemDeleteService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemDeleteRequest) (*core.Item, error)) *MockItemDeleteService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemGetService creates a new instance of MockItemGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemGetService {
	mock := &MockItemGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemGetService is an autogenerated mock type for the ItemGetService type
type MockItemGetService struct {
	mock.Mock
}

type MockItemGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemGetService) EXPECT() *MockItemGetService_Expecter {
	return &MockItemGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemGetService
func (_mock *MockItemGetService) Exec(ctx context.Context, request *core.ItemGetRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemGetRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemGetRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemGetRequest
func (_e *MockItemGetService_Expecter) Exec(ctx any, request any) *MockItemGetService_Exec_Call {
	return &MockItemGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemGetService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemGetRequest)) *MockItemGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemGetService_Exec_Call) Return(item *core.Item, err error) *MockItemGetService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemGetRequest) (*core.Item, error)) *MockItemGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemListService creates a new instance of MockItemListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemListService {
	mock := &MockItemListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemListService is an autogenerated mock type for the ItemListService type
type MockItemListService struct {
	mock.Mock
}

type MockItemListService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemListService) EXPECT() *MockItemListService_Expecter {
	return &MockItemListService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemListService
func (_mock *MockItemListService) Exec(ctx context.Context, request *core.ItemListRequest) ([]*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemListRequest) ([]*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemListRequest) []*core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemListService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemListService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemListRequest
func (_e *MockItemListService_Expecter) Exec(ctx any, request any) *MockItemListService_Exec_Call {
	return &MockItemListService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemListService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemListRequest)) *MockItemListService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemListRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemListService_Exec_Call) Return(items []*core.Item, err error) *MockItemListService_Exec_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemListService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemListRequest) ([]*core.Item, error)) *MockItemListService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemUpdateService creates a new instance of MockItemUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemUpdateService {
	mock := &MockItemUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemUpdateService is an autogenerated mock type for the ItemUpdateService type
type MockItemUpdateService struct {
	mock.Mock
}

type MockItemUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemUpdateService) EXPECT() *MockItemUpdateService_Expecter {
	return &MockItemUpdateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockItemUpdateService
func (_mock *MockItemUpdateService) Exec(ctx context.Context, request *core.ItemUpdateRequest) (*core.Item, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemUpdateRequest) (*core.Item, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.ItemUpdateRequest) *core.Item); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.ItemUpdateRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemUpdateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockItemUpdateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ItemUpdateRequest
func (_e *MockItemUpdateService_Expecter) Exec(ctx any, request any) *MockItemUpdateService_Exec_Call {
	return &MockItemUpdateService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockItemUpdateService_Exec_Call) Run(run func(ctx context.Context, request *core.ItemUpdateRequest)) *MockItemUpdateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.ItemUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*core.ItemUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemUpdateService_Exec_Call) Return(item *core.Item, err error) *MockItemUpdateService_Exec_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemUpdateService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.ItemUpdateRequest) (*core.Item, error)) *MockItemUpdateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
