// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-jobs/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobClaimService creates a new instance of MockJobClaimService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobClaimService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobClaimService {
	mock := &MockJobClaimService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobClaimService is an autogenerated mock type for the JobClaimService type
type MockJobClaimService struct {
	mock.Mock
}

type MockJobClaimService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobClaimService) EXPECT() *MockJobClaimService_Expecter {
	return &MockJobClaimService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobClaimService
func (_mock *MockJobClaimService) Exec(ctx context.Context, request *core.JobClaimRequest) ([]*core.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*core.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobClaimRequest) ([]*core.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobClaimRequest) []*core.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JobClaimRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobClaimService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobClaimService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JobClaimRequest
func (_e *MockJobClaimService_Expecter) Exec(ctx any, request any) *MockJobClaimService_Exec_Call {
	return &MockJobClaimService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobClaimService_Exec_Call) Run(run func(ctx context.Context, request *core.JobClaimRequest)) *MockJobClaimService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JobClaimRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JobClaimRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobClaimService_Exec_Call) Return(jobs []*core.Job, err error) *MockJobClaimService_Exec_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobClaimService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JobClaimRequest) ([]*core.Job, error)) *MockJobClaimService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobEnqueueService creates a new instance of MockJobEnqueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobEnqueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobEnqueueService {
	mock := &MockJobEnqueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobEnqueueService is an autogenerated mock type for the JobEnqueueService type
type MockJobEnqueueService struct {
	mock.Mock
}

type MockJobEnqueueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobEnqueueService) EXPECT() *MockJobEnqueueService_Expecter {
	return &MockJobEnqueueService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobEnqueueService
func (_mock *MockJobEnqueueService) Exec(ctx context.Context, request *core.JobEnqueueRequest) (*core.JobEnqueueResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.JobEnqueueResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobEnqueueRequest) (*core.JobEnqueueResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobEnqueueRequest) *core.JobEnqueueResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.JobEnqueueResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JobEnqueueRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobEnqueueService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobEnqueueService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JobEnqueueRequest
func (_e *MockJobEnqueueService_Expecter) Exec(ctx any, request any) *MockJobEnqueueService_Exec_Call {
	return &MockJobEnqueueService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobEnqueueService_Exec_Call) Run(run func(ctx context.Context, request *core.JobEnqueueRequest)) *MockJobEnqueueService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JobEnqueueRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JobEnqueueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobEnqueueService_Exec_Call) Return(jobEnqueueResult *core.JobEnqueueResult, err error) *MockJobEnqueueService_Exec_Call {
	_c.Call.Return(jobEnqueueResult, err)
	return _c
}

func (_c *MockJobEnqueueService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JobEnqueueRequest) (*core.JobEnqueueResult, error)) *MockJobEnqueueService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobGetService creates a new instance of MockJobGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobGetService {
	mock := &MockJobGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobGetService is an autogenerated mock type for the JobGetService type
type MockJobGetService struct {
	mock.Mock
}

type MockJobGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobGetService) EXPECT() *MockJobGetService_Expecter {
	return &MockJobGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobGetService
func (_mock *MockJobGetService) Exec(ctx context.Context, request *core.JobGetRequest) (*core.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobGetRequest) (*core.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobGetRequest) *core.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JobGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JobGetRequest
func (_e *MockJobGetService_Expecter) Exec(ctx any, request any) *MockJobGetService_Exec_Call {
	return &MockJobGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobGetService_Exec_Call) Run(run func(ctx context.Context, request *core.JobGetRequest)) *MockJobGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JobGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JobGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobGetService_Exec_Call) Return(job *core.Job, err error) *MockJobGetService_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JobGetRequest) (*core.Job, error)) *MockJobGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobSettleService creates a new instance of MockJobSettleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobSettleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobSettleService {
	mock := &MockJobSettleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobSettleService is an autogenerated mock type for the JobSettleService type
type MockJobSettleService struct {
	mock.Mock
}

type MockJobSettleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobSettleService) EXPECT() *MockJobSettleService_Expecter {
	return &MockJobSettleService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobSettleService
func (_mock *MockJobSettleService) Exec(ctx context.Context, request *core.JobSettleRequest) (*core.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobSettleRequest) (*core.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobSettleRequest) *core.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JobSettleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobSettleService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobSettleService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JobSettleRequest
func (_e *MockJobSettleService_Expecter) Exec(ctx any, request any) *MockJobSettleService_Exec_Call {
	return &MockJobSettleService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobSettleService_Exec_Call) Run(run func(ctx context.Context, request *core.JobSettleRequest)) *MockJobSettleService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JobSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JobSettleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobSettleService_Exec_Call) Return(job *core.Job, err error) *MockJobSettleService_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobSettleService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JobSettleRequest) (*core.Job, error)) *MockJobSettleService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobWatchService creates a new instance of MockJobWatchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobWatchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobWatchService {
	mock := &MockJobWatchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobWatchService is an autogenerated mock type for the JobWatchService type
type MockJobWatchService struct {
	mock.Mock
}

type MockJobWatchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobWatchService) EXPECT() *MockJobWatchService_Expecter {
	return &MockJobWatchService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockJobWatchService
func (_mock *MockJobWatchService) Exec(ctx context.Context, request *core.JobGetRequest) (*core.Job, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobGetRequest) (*core.Job, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.JobGetRequest) *core.Job); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.JobGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobWatchService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockJobWatchService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.JobGetRequest
func (_e *MockJobWatchService_Expecter) Exec(ctx any, request any) *MockJobWatchService_Exec_Call {
	return &MockJobWatchService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockJobWatchService_Exec_Call) Run(run func(ctx context.Context, request *core.JobGetRequest)) *MockJobWatchService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.JobGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.JobGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobWatchService_Exec_Call) Return(job *core.Job, err error) *MockJobWatchService_Exec_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobWatchService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.JobGetRequest) (*core.Job, error)) *MockJobWatchService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
